### ISSUE TITLE
ModuleNotFoundError: No module named 'src.Config'

### ISSUE THREAD

**Issue by lucas-torres** [GGServers/Platypus#8]
Above, the error when i trying install
> C:\>python setup.py
> Traceback (most recent call last):
>   File "setup.py", line 2, in <module>
>     from src.Config import Config
> ModuleNotFoundError: No module named 'src.Config'

**Comment by gmemstr** [comment]
Looking into this ASAP. Thanks.

**Comment by gmemstr** [comment]
@lucas-torres Unable to replicate this issue, how did you clone the repository? Could you do a quick directory listing of `src/` as well?

**Comment by structief** [comment]
Same issue here, this is the listing for `src/`:
- Aor.py  
- cache 
- Config.py 
- ServerHandler.py  
- Slackbot.py  
- static  
- templates  
- Tornado.py

**Comment by gmemstr** [comment]
@kliptonize Odd, I don't seem to be able to replicate this either by downloading a fresh latest release or cloning the repository. Could you copy the contents of `Config.py` into a reply? Really want to get to the bottom of this.

**Comment by gmemstr** [comment]
Okay, cloning to a fresh VPS seems to produce the same issue, I will be taking a closer look at this tonight and should have a solution pushed out tomorrow (if my power sticks around).

**Comment by gmemstr** [comment]
Update: @kliptonize @lucas-torres Would you guys mind doing a `python --version` just to confirm a suspicion I have? This bug may be due to Python 2 not having the same import methodology as Python 3 (in which Platypus is developed, and is made clear through the docs).

**Comment by structief** [comment]
Sure thing, mine is `Python 2.7.12`, shall I update, or wait for a fix?

_(Installed `Python 3.5.2` next to it, throws a `ImportError: No module named 'MySQLdb'` error)_

**Comment by lucas-torres** [comment]
`Python 3.6.2 :: Anaconda, Inc.` Here

**Comment by gmemstr** [comment]
@kliptonize You'll want to run `pip install -r requirements.txt`

@lucas-torres Looking into this if it's persisting on Python 3.6.2

**Comment by structief** [comment]
Sadly, the problem remains, even after the `pip install` command tells me all requirements are satisfied

**Comment by gmemstr** [comment]
@kliptonize Pip might still be trying to install dependencies for Python 2 to use, try following this on SO https://stackoverflow.com/questions/11268501/how-to-use-pip-with-python-3-x-alongside-python-2-x

**Comment by gmemstr** [comment]
Tracked down the root of the problem: for some reason the __init__.py file is missing and causing import errors in fresh install of Python, even though my dev env handles it fine. Weird, but pushing fix now.

**Comment by gmemstr** [comment]
Pushed out fix, closing issue as I have verified it in clean env. Feel free to reopen if it does persist.

(git pull or download new tagged release)
