### ISSUE TITLE
Website DOWN

### ISSUE THREAD

**Issue by davidak** [GGServers/Platypus#9]
http://getplatypus.io/
The domain could not get resolved!

Is this project dead?

**Comment by gmemstr** [comment]
This project has been long deprecated unfortunately, I let the domain expire as well.

Feel free to pick it up, for the most part I'm not working on this project any more unless something motivates me to.

Sorry about that.

**Comment by davidak** [comment]
OK. Thanks for the response. Could you add a hint in the readme about the status and remove the domain?
